### ISSUE TITLE
Sqlite support

### ISSUE THREAD

**Issue by mikfaina** [mevdschee/php-crud-api#405] opened 2018-08-06 10:26 UTC
Is there still support for sqlite in v2? I can't see any reference anymore

**Comment by mevdschee** [comment] 2018-08-07 05:49
v2 is a complete rewrite and this is not yet implemented.

**Comment by mevdschee** [comment] 2020-04-02 12:28
I'm willing to (re)add sqlite support if there is enough interest in it. Note that it is not working/perfoming well for large databases (with lots of tables), due to the costly reflection step that has to be executed. Other than that I think it is feasible.

**Comment by thipages** [comment] 2020-04-02 12:38
Hi,
the shema is/can be cached?

**Comment by mevdschee** [comment] 2020-04-02 12:41
Yes hopefully the new caching mechanism will make it performant (enough).

**Comment by mikfaina** [comment] 2020-04-02 13:02
I'm interested

**Comment by focussing** [comment] 2020-04-02 13:03
Hello @mevdschee I am certainly interested. What do you mean with binary support? BLOBs?

**Comment by mevdschee** [comment] 2020-04-02 13:05
>What do you mean with binary support? BLOBs?

Yes, I believe there is no BLOB support.

**Comment by focussing** [comment] 2020-04-02 13:06
Perfect!

**Comment by mevdschee** [comment] 2020-04-03 20:20
The first 69 tests succeed.. I'll try to finish this weekend.

**Comment by mevdschee** [comment] 2020-04-03 23:21
Most tests succeed.. please try master and see whether or not it works for you.

Use "address" for the sqlite filename and "database" should not be empty.

**Comment by mevdschee** [comment] 2020-04-03 23:31
Performance seems to be "okay", I'll let you decide:

    mysql: 79 tests ran in 1952 ms, 0 failed
    sqlite: 78 tests ran in 2822 ms, 0 failed

Tested on a small database with only 14 tables.

**Comment by mevdschee** [comment] 2020-04-04 14:18
It seems that online table/column modifications are not supported (you need to recreate the table/column and copy the data). See: https://www.techonthenet.com/sqlite/foreign_keys/drop.php

This may be a problem for the sqlite support/performance in the admin variant of this script.

**Comment by focussing** [comment] 2020-04-06 06:38
Good morning @mevdschee you're speeding!!

I added at the end of api.php the sqlite database file

```
    $config = new Config([
        'username' => 'php-crud-api',
        'password' => 'php-crud-api',
        'database' => 'php-crud-api',
        'address' => './rc.sqlite'
    ]);
```
Started a php server on port 2222 (I have Vue.js running at 8080).
My database file has one table called `logfile` with 8 columns.
Browser `http://localhost:2222/api.php/records/logfile/7800` gives an error

```
{
code: 9999
}
```

Almost all other calls like `http://localhost:2222/api.php/logfile/7800` give

```
{
code: 1000,
message: "Route '/logfile/7800' not found"
}
```

It seems that I am close, but still missing something... Could you help me please?

**Comment by mevdschee** [comment] 2020-04-06 07:03
Can you enable debug mode? In the config set:

    "debug" => true

Note that "http://localhost:2222/api.php/logfile/7800" is the wrong URL scheme, so that 404 is expected.

**Comment by mevdschee** [comment] 2020-04-06 07:05
Please be sure to download the latest version from master (of this morning).

**Comment by focussing** [comment] 2020-04-06 07:32
I just downloaded the master version, set the debug option, but same result.
By the way where can I see debug statements?

What is wrong with the URL scheme?
logfile is the table
7800 is the ID of one record in the database

**Comment by mevdschee** [comment] 2020-04-06 07:33
> By the way where can I see debug statements?

In the response headers.

**Comment by mevdschee** [comment] 2020-04-06 07:33
The url: http://localhost:2222/api.php/logfile/7800

should be: http://localhost:2222/api.php/records/logfile/7800

**Comment by focussing** [comment] 2020-04-06 07:38
Yep that's what I did.

**Comment by focussing** [comment] 2020-04-06 07:38
Connection: close
Content-Length: 13
Content-Type: application/json
Date: Mon, 06 Apr 2020 07:38:07 +0000
Host: localhost:2222
X-Exception-File: /Users/raymond/stack/sites/php-crud-api-master/api.php:6362
X-Exception-Message: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known
X-Exception-Name: PDOException
X-Powered-By: PHP/7.1.23

**Comment by focussing** [comment] 2020-04-06 07:48
Also tried it online (aside where my old php script resides) returns Http error 500...

**Comment by mevdschee** [comment] 2020-04-06 07:49
Please do set:

    'driver' => 'sqlite',

Otherwise it tries to connect to mysql.

**Comment by focussing** [comment] 2020-04-06 07:53
That did the trick! Beautiful. And fast!

**Comment by mevdschee** [comment] 2020-04-06 07:57
Note that this support is not official yet.. it may see some refactoring and performance improvements (admin is very very slow). I will also add it to the tests and to the dockers (for cross platform testing).

**Comment by focussing** [comment] 2020-04-06 07:57
Maybe some small adjustments to do; it returns
```
{
  id: 7800,
  date: 2020,
  serialnr: 29,
  fw_version: 0,
  sw_version: 0,
  testbox_id: 0,
  testerrors: 100000000,
  current_meas: 0
}
```

Whereas my original script returns
```
[
{
  id: "7800",
  date: "2020-04-04 08:38:04",
  serialnr: "0000029yywwddnnn",
  fw_version: "RCIL_ser_07V001g",
  sw_version: "0.2.1.7",
  testbox_id: "T-16xx",
  testerrors: "0000000100000000",
  current_meas: "[7,7,13,13,13,12,11,13,13,13,11,11,12,7,11,11,11,11,11,11,10,11,10,11,11,10,11,7]"
}
]
```

**Comment by mevdschee** [comment] 2020-04-06 08:01
Can you post the create script (SQL) of the table?

**Comment by focussing** [comment] 2020-04-06 08:05
CREATE TABLE logfile (id integer  PRIMARY KEY AUTOINCREMENT DEFAULT NULL,date TEXT,serialnr TEXT DEFAULT NULL,fw_version TEXT  NOT NULL,sw_version TEXT DEFAULT NULL,testbox_id TEXT DEFAULT NULL,testerrors TEXT DEFAULT NULL,current_meas TEXT)

**Comment by focussing** [comment] 2020-04-06 08:06
The old script sees the fields are text

**Comment by mevdschee** [comment] 2020-04-06 08:06
Ah.. the new script should do that as well.. it seems this is a bug.

**Comment by mevdschee** [comment] 2020-04-06 08:15
I'm able to reproduce.. give me a minute.. I'll update master with a bugfix soon..

**Comment by focussing** [comment] 2020-04-06 08:16
Considering the speed you implemented sqlite... only compliments...

**Comment by mevdschee** [comment] 2020-04-06 08:25
It is done.. I tested only with lowercase types..

**Comment by focussing** [comment] 2020-04-06 08:40
Great job!!

Your scripts perfectly responds taking into account the column types, which the old script doesn't.

Also the JSON respond is different (one element consisting of records array) compared to one array, so I need to check how the frontend of my projects deal with that.
Or is there a built-in config setting that can influence this?
I see in "batch processing" that there only an array is returned.

**Comment by mevdschee** [comment] 2020-04-06 12:19
> Or is there a built-in config setting that can influence this?

No, unfortunately not.

Let me know whether or not this works for you.

**Comment by focussing** [comment] 2020-04-07 05:25
Yes @mevdschee it works!
Did testing yesterday and you've done a great job in such a short amount of time 👍 

What is the reason that the url is .../api.php/records/table_name/... and the reply JSON is one object `records` holding the results array?
And what is the reason that when using "batch processing" only the results array is returned?

This looks like a contradiction; always returning a results array should be enough wouldn't it?

**Comment by mevdschee** [comment] 2020-04-07 06:07
>This looks like a contradiction; always returning a results array should be enough wouldn't it?

It is there so that in pagination there is room for extra result variables (such as count) outside the data.

**Comment by focussing** [comment] 2020-04-07 06:55
That makes perfectly sense.
Thanks again for this great api... 👍

**Comment by focussing** [comment] 2020-04-07 06:56
Are there any issues that you know of that I should take about?
Apart from `It seems that online table/column modifications are not supported (you need to recreate the table/column and copy the data). ` you mention above.

**Comment by mevdschee** [comment] 2020-04-07 09:28
I am not done with the part of the API that modifies columns and tables (structure), but I'm done with the data part. I have done a big improvement just now that does not need temporary "sys/*" tables and is much faster.

**Comment by focussing** [comment] 2020-04-07 09:47
OK pls keep me informed as I can do some testing easily if you want me to 👍

**Comment by mevdschee** [comment] 2020-04-07 14:56
It seems there are no open issues anymore in the "/records" part. Note that you cannot have a bigint as auto incrementing primary key. This is a strange sqlite limitation that I ran into.

**Comment by mevdschee** [comment] 2020-04-07 17:24
v2.6.8 is released containing the first version of the sqlite implementation. Documentation will follow.

**Comment by mevdschee** [comment] 2020-04-07 17:29
Performance update:

    maurits@maurits-desktop:~/projects/php-crud-api$ php test.php mysql 001
    mysql: 85 tests ran in 2481 ms, 0 failed
    maurits@maurits-desktop:~/projects/php-crud-api$ php test.php sqlite 001
    sqlite: 81 tests ran in 2809 ms, 0 failed

As you can see the sqlite implementation is only a little slower than mysql.

**Comment by mevdschee** [comment] 2020-04-08 23:46
Problems/known issues so far:

- You need SQLite 3.16 or higher for pragma table functions to work (those are needed for good performance). 
- Also since I am using the PDO driver I cannot support spatial features (with Spatialite) nor binary, which is a pity. 
- Since online table modifications are not fully supported in SQLite (alter table) you should expect the structure updates to fail.

The documentation is updated.

**Comment by thipages** [comment] 2020-04-08 23:49
Hi,
I am bit late here. Will test later and give feedbacks
congrat!

**Comment by mevdschee** [comment] 2020-04-09 00:00
Performance difference between mysql 8 and sqlite 3.31 is almost zero on Ubuntu 20.04:

    root@2b8febcb9873:/php-crud-api# php test.php mysql 001
    mysql: 85 tests ran in 891 ms, 0 skipped, 0 failed
    root@2b8febcb9873:/php-crud-api# php test.php sqlite 001
    sqlite: 85 tests ran in 785 ms, 4 skipped, 0 failed

Results come in a little faster on sqlite, but it also skippes a few tests, no noticable difference.

**Comment by mevdschee** [comment] 2020-04-13 21:43
I'll close this now, as the implementation is complete. I know it is still missing binary and geospatial support. For geospatial support, please see ticket #642

**Comment by mevdschee** [comment] 2020-04-13 23:57
@focussing I wrote a blog post announce the (re)added sqlite support:

https://tqdev.com/2020-php-crud-api-v2-now-supports-sqlite

feel free to send me comments/improvements.

**Comment by mevdschee** [comment] 2020-04-21 09:52
@focussing I have released v2.8.1 with more consistent type handling in SQLite (and SQL Server). Can you confirm that it works well for you?

**Comment by focussing** [comment] 2020-04-22 04:50
I will check this next week, thanks!

Best regards, 
Mit freundlichen Grüßen,
Met vriendelijke groet,
Raymond Verbruggen

FOCUSSING B.V.
Mispel 8
7621 WB Borne
Netherlands
+31 6 250 500 69 
mail@focussing.nl <mailto:mail@focussing.nl> 
www.focussing.nl <http://www.focussing.nl/>

**Comment by focussing** [comment] 2020-04-30 10:18
Hi Maurits,

I checked the latest release 2.9.1 but it is not working for my application, I can send you the links to see if you want (not in public).

The call is:

.../api.php/records/testdata/?order=id,desc&size=10 <http://update.vbairsuspension.com/testtool/api.php/records/testdata/?order=id,desc&size=10>

And

…/api-old.php/records/testdata/?order=id,desc&size=10 <http://update.vbairsuspension.com/testtool/api.php/records/testdata/?order=id,desc&size=10>

The old version gives this:

{
records: [
{
id: 10131,
analog_minmax: "[949,1,954,1,959,1,955,1,960,1,961,0,956,1,959,1,789,191,793,190]",
analog_pwm: "[474,476,455,452,464,466,473,473,553,558]",
ascu_id: "0000000000000000",
date: "22-04-2020 16:12:49",
fw_version: "TestTool_90V009d",
device_type: "2593",
misc: "[0,0,0,0,0,0,0,0]",
sw_version: "1.0.2.5",
test_status: "ASCU test FAILED",
test_target: "Coulance",
testbox_id: "T-0844",
testerrors: "[0,0,0,8192]",
username: "Extern",
voltages: "[13.63,517,504,1574]",
device_id: "nvt"
},
{


and with 2.9.1 the result is:

{
code: 9999
}

What am I doing wrong?


Best regards, 
Mit freundlichen Grüßen,
Met vriendelijke groet,
Raymond Verbruggen
 
FOCUSSING B.V.
Mispel 8
7621 WB Borne
Netherlands
+31 6 250 500 69 
mail@focussing.nl 
www.focussing.nl

**Comment by mevdschee** [comment] 2020-04-30 11:58
Code 9999 can mean a lot, you need to enable debug setting and then post the full response including the response headers. Also you may post the create statement of the table, so that I can try to reproduce.

**Comment by mevdschee** [comment] 2020-05-02 06:17
Can you try the latest (v2.9.2 Default type to clob)?

**Comment by focussing** [comment] 2020-05-04 07:38
Same error...

The response headers:

Content-Length: 13
Content-Type: application/json
Date: Mon, 04 May 2020 07:36:48 GMT
Server: nginx
X-Exception-File: /var/www/vhosts/vbairsuspension.com/update.vbairsuspension.com/testtool/api-292.php:6357
X-Exception-Message: SQLSTATE[HY000]: General error: 1 near "(": syntax error
X-Exception-Name: PDOException
X-Powered-By: PHP/7.2.16

**Comment by mevdschee** [comment] 2020-05-04 16:34
Can you post the create statement of the table, so that I can try to reproduce the problem?

**Comment by mevdschee** [comment] 2020-05-04 16:35
What version is the "old version"?

**Comment by focussing** [comment] 2020-05-04 18:38
CREATE TABLE logfile (id integer PRIMARY KEY AUTOINCREMENT DEFAULT NULL,date TEXT,serialnr TEXT DEFAULT NULL,fw_version TEXT NOT NULL,sw_version TEXT DEFAULT NULL,testbox_id TEXT DEFAULT NULL,testerrors TEXT DEFAULT NULL,current_meas TEXT)

**Comment by focussing** [comment] 2020-05-04 18:44
What version? I don't know, creation date says april 6...
[api.php.zip](https://github.com/mevdschee/php-crud-api/files/4576626/api.php.zip)

**Comment by mevdschee** [comment] 2020-05-04 18:45
Thank you for your replies.. I'm on it!

**Comment by mevdschee** [comment] 2020-05-04 18:52
What is your sqlite version?

**Comment by mevdschee** [comment] 2020-05-04 19:00
The current version supports:

> SQLite 3.16 or higher (spatial features NOT supported)

Maybe you are running Ubuntu 16.04 with SQLite 3.12?

The old version (and v1) did support that older version, but it performed really bad, so now 3.16 is required so that no 'fake' reflection tables have to be created.

**Comment by focussing** [comment] 2020-05-04 20:05
The server is one year old; running Centos 7 with PHP 7.2. I'll have to check more tomorrow

**Comment by focussing** [comment] 2020-05-04 20:06
sqlite 3.7?

**Comment by focussing** [comment] 2020-05-04 20:10
how can I check that easily?

**Comment by mevdschee** [comment] 2020-05-04 20:19
Centos 7 indeed runs SQLite 3.7.17 (2013-05-20, that is about 7 years old). Centos 8 runs 3.26.0 (2018-12-01, about one and a half year old). I think that the version is the problem. I can add some version detection, but I'm afraid for false negatives on the version test(s).

**Comment by mevdschee** [comment] 2020-05-04 20:21
Maybe this link can help (use at your own risk)?

https://linuxhint.com/upgrade-to-latest-sqlite3-on-centos7/

**Comment by mevdschee** [comment] 2020-05-04 20:22
> how can I check that easily?

With this statement on the command line:

     sqlite3 --version

Please post the output.

**Comment by mevdschee** [comment] 2020-05-04 20:50
I'm afraid upgrading SQLite on CentOS 7 is too tricky to recommend. Upgrading the server to CentOS 8 would be my recommendation.

**Comment by focussing** [comment] 2020-05-05 05:17
sqlite3 --version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668

In my database I see also some tables I didn't notice before:

![Schermafbeelding 2020-05-05 om 07 10 48](https://user-images.githubusercontent.com/26736152/81036508-a953b100-8e9f-11ea-8371-fec12e8194a8.png)

Updating my server to Centos8 is not an option; I wouldn't take the chance my customers having troubles with their domains.

Did you manage to figure out what (working) version I currently use?

**Comment by focussing** [comment] 2020-05-05 05:25
Scrolled all the way up and I think it is the version that was master dd 6 april 10:40.
Is there a way to "ask" api.php what version it is?

**Comment by focussing** [comment] 2020-05-05 05:46
I did a quick test using 2.6.8:
```
{
code: 9999
}
```

Response headers:
```
Connection: keep-alive
Content-Length: 13
Content-Type: application/json
Date: Tue, 05 May 2020 05:43:12 GMT
Server: nginx
X-Powered-By: PHP/7.2.16
```
I think my version is a one off that I should be very careful with...

**Comment by mevdschee** [comment] 2020-05-05 05:56
> Is there a way to "ask" api.php what version it is?

There is no way to "ask" api.php what version it is.

>I think my version is a one off that I should be very careful with...

Yes, the version of April 6th was never released as an official version (although you are free to run it). 

>In my database I see also some tables I didn't notice before:

The "sys/*" tables are created as a workaround for missing reflection functionality by the script. 

Since that method does not perform well, it is no longer using those tables and is now using a reflection method that was introduced in SQLite 3.16.

You can read this:

https://sqlite.org/changes.html

and look for:

    Added experimental support for PRAGMA functions. 

This is introduced in 2017-01-02 (3.16.0)

**Comment by focussing** [comment] 2020-05-05 06:08
Well, the April 6th version was the best...

I reproduced a zip file of the release using my backup files so at least I have something... [php-crud-api-master.zip](https://github.com/mevdschee/php-crud-api/files/4579091/php-crud-api-master.zip)

Thanks for your help.

**Comment by mevdschee** [comment] 2020-05-05 06:42
I made a branche for you:

https://github.com/mevdschee/php-crud-api/tree/focussing

It will never be official as the performance is *really* bad.

**Comment by mevdschee** [comment] 2020-05-05 06:54
You can see a factor 10 difference in the tests:

    maurits@maurits-desktop:~/projects/php-crud-api$ git checkout focussing 
    Switched to branch 'focussing'
    Your branch is up to date with 'origin/focussing'.
    maurits@maurits-desktop:~/projects/php-crud-api$ php test.php sqlite
    sqlite: 109 tests ran in 38999 ms, 12 skipped, 0 failed
    maurits@maurits-desktop:~/projects/php-crud-api$ git checkout master
    Switched to branch 'master'
    Your branch is up to date with 'origin/master'.
    maurits@maurits-desktop:~/projects/php-crud-api$ php test.php sqlite
    sqlite: 109 tests ran in 4401 ms, 12 skipped, 0 failed
    maurits@maurits-desktop:~/projects/php-crud-api$ 

I hope it is not too bad for you in production.

**Comment by mevdschee** [comment] 2020-05-05 07:35
>Thanks for your help.

Thank you for helping me bring back SQLite support to PHP-CRUD-API, appreciated!

**Comment by focussing** [comment] 2020-05-06 07:32
You're welcome :)

Thank you for making a branch. You mentioned having considered a version detection; would that the solution for a merge?

Quite a diff in speed indeed! In my case the performance is not an issue (yet). Especially because pagination is supported.

One usage question: is there a way to combine the "count" function with a "where" clause using this api?

**Comment by mevdschee** [comment] 2020-05-06 07:35
>is there a way to combine the "count" function with a "where" clause using this api?

Only indirect: you can create a view with a "count" function in it and access that with a filter.

**Comment by mevdschee** [comment] 2020-05-06 07:44
>Thank you for making a branch. You mentioned having considered a version detection; would that the solution for a merge?

No, it would be to warn that the software cannot run. Such slow performance would only raise questions and issues, like it did in the past.

**Comment by mevdschee** [comment] 2020-10-03 19:28
@focussing Have you upgraded to a newer version of SQLite? I'm thinking of closing this issue and removing the branch as it is also unmaintained.

**Closed** 2020-10-03 19:30 UTC
Labels: enhancement

**Comment by focussing** [comment] 2020-10-04 12:11
@mevdschee Thank you!!
