### ISSUE TITLE
Error 9999

### ISSUE THREAD

**Issue by educkf** [mevdschee/php-crud-api#545] opened 2019-05-24 19:32 UTC
Hi there!
I am trying to add some content to a Table using POST, and I getting this error message, but I can't understand properly what might be the issue so I can correct it:

{"code":9999,"message":"Return value of Tqdev\\PhpCrudApi\\SimpleRouter::handle() must implement interface Tqdev\\PhpCrudApi\\ResponseInterface, null returned"}

I receive it even if I submit the form as blank, the error is the same.
Any idea what it might be?

Thanks!

**Comment by mevdschee** [comment] 2019-05-26 19:07
Thank you for reporting this issue. In order for me/us to reproduce, please add the exact request you are doing and a dump op the table structure you are doing this on. That way the issue is easier to reproduce.

**Comment by geezer78** [comment] 2019-05-28 05:37
Hi There, 
i'm also seeing this error and have narrowed it down to the situation where I send an empty value to a database field that does not have a default value.

hope this helps!

btw: great job Maurits this api saves me a ton of time!

**Comment by mevdschee** [comment] 2019-05-28 07:02
Thank you @geezer78! Can one of you two provide a test case for me?

**Comment by mevdschee** [comment] 2019-07-09 15:03
I've tried to reproduce, but without success. Although I really appreciate the report, I'm closing this for now until a test case is provided (You can add a file to the `tests/functional/001_records` folder).

**Closed by mevdschee** 2019-07-09 15:03 UTC
Labels: help wanted
