### ISSUE TITLE
php-crud-api filter usage problems

### ISSUE THREAD

**Issue by zhao666888** [mevdschee/php-crud-api#637] opened 2020-04-07 05:21 UTC
Hello:
        I seem to have found some problems during  the use, 
        ![image](https://user-images.githubusercontent.com/41735559/78632343-5b17b600-78d1-11ea-807f-66b52b1be7bf.png)
        As shown in the figure, I query that the destination equals 2 and the planappstage equals 20,but it seems that a value with destination equal to 3 appears in the returned result,this is not what we expected.I really hope to get your help. This question bothers me a lot.
        Thank you for your answer.

**Comment by mevdschee** [comment] 2020-04-07 06:19
Try using parameters named "filter1" and "filter2" instead of all "filter", because now it is doing "OR" and when you number the filter parameters it will do "AND".

**Comment by zhao666888** [comment] 2020-04-07 06:47
Hi:
    Thank you for your reply, but I see it in the document.
    https://github.com/mevdschee/php-crud-api#multiple-filters
   ![image](https://user-images.githubusercontent.com/41735559/78638277-940a5780-78de-11ea-9e5c-921eedd10e3b.png)

**Comment by mevdschee** [comment] 2020-04-07 09:27
Oops.. I think you are correct. Thank you! Let me examine this.

**Comment by zhao666888** [comment] 2020-04-07 09:29
Thank you for your answer

**Comment by mevdschee** [comment] 2020-04-07 10:16
I tried to reproduce this issue, but I can't.. Can you help me? Maybe post the table structure and the query and the actual and expected results?

**Comment by mevdschee** [comment] 2020-04-07 12:16
My bad, this was a fix for #636

**Comment by mevdschee** [comment] 2020-04-07 17:20
I really tried to reproduce this issue, but I can't. Can you help me?

**Comment by zhao666888** [comment] 2020-04-10 02:57
I'm really sorry. I didn't see the reply yesterday. I'm very sorry，Thank you very much for your reply. We are very willing to help solve this problem. At present, we have located the problem，
For example, this request：http://idptest.cacov.cn/api/records/idp_userInfo?filter=destination,eq,2&filter=planAppStage,eq,20，There are two filters，When receiving the request, the first filter will be automatically overwritten. I think that's the problem. We use laravel

**Comment by zhao666888** [comment] 2020-04-10 02:58
I think such a question should not be distinguished from a certain framework. I look forward to your reply and I will reply in time

**Comment by mevdschee** [comment] 2020-04-10 07:07
Can you look for this line:

    $query = str_replace('][]=', ']=', str_replace('=', '[]=', $query));

And replace with:

    $query = str_replace('%5D%5B%5D=', '%5D=', str_replace('=', '%5B%5D=', $query));

Does that help? I think it is a bug.

**Comment by zhao666888** [comment] 2020-04-10 09:53
![image](https://user-images.githubusercontent.com/41735559/78981966-a6d99200-7b53-11ea-9cab-a05665f699d9.png)
We use laravel, such as the link address:http://idptest.cacov.cn/api/records/idp_userInfo?filter=destination,eq,2&filter=planAppStage,eq,20, the first filter has been overwritten when request is obtained, and only the second filter is obtained.
![image](https://user-images.githubusercontent.com/41735559/78982182-2bc4ab80-7b54-11ea-9f78-7b412e4dee66.png)

**Comment by zhao666888** [comment] 2020-04-10 09:55
![image](https://user-images.githubusercontent.com/41735559/78982294-6595b200-7b54-11ea-97a1-56efd6a8dca3.png)

**Comment by mevdschee** [comment] 2020-04-10 12:18
>Does that help?

Did you try what I recommended? What is the output of your debug command?

Did you try the request with square brackets? Change:

http://idptest.cacov.cn/api/records/idp_userInfo?filter=destination,eq,2&filter=planAppStage,eq,20

into:

http://idptest.cacov.cn/api/records/idp_userInfo?filter[]=destination,eq,2&filter[]=planAppStage,eq,20

Let me know all three answers please.

**Comment by mevdschee** [comment] 2020-04-10 13:20
v2.7.3 is released with a fix for the failing square brackets.

**Comment by zhao666888** [comment] 2020-04-13 09:21
With v2.6.7, our request will throw an exception:
`{"code":9999,"message":"Argument 2 passed to Tqdev\\PhpCrudApi\\Record\\Condition\\Condition::fromString() must be of the type string, array given, called in \/home\/wwwroot\/idp-wxUser\/vendor\/mevdschee\/php-crud-api\/src\/Tqdev\/PhpCrudApi\/Record\/FilterInfo.php on line 18"}`
We received your reply and upgraded the version to v2.7.3. We found that this problem has been solved perfectly. Thank you very much for your help.

**Comment by mevdschee** [comment] 2020-04-13 10:16
Thank you for reporting back. I'm happy that your problem is solved. Enjoy the software!

**Closed by mevdschee** 2020-04-13 10:16 UTC
Labels: bug
