### ISSUE TITLE
Group a table

### ISSUE THREAD

**Issue by zhao666888** [mevdschee/php-crud-api#622] opened 2020-02-21 07:19 UTC
Hi,
There is no grouping operation found in the document. How can I implement grouping

**Comment by lcuis** [comment] 2020-02-21 07:45
Hello @zhao666888 

Views provide a way to group for php-crud-api .
Dup #601

**Comment by zhao666888** [comment] 2020-02-21 08:02
hi,lcuis
Can you tell me how to implement it in API，Like this one SQL 'select * from groupBy mobile'。
thank you very much indeed

**Comment by mevdschee** [comment] 2020-02-21 08:07
You can create a view with:

    create view my_view as select ...

See: https://dev.mysql.com/doc/refman/8.0/en/create-view.html

**Comment by zhao666888** [comment] 2020-02-21 08:34
Hi:
Thank you very much for your prompt reply，
I think I understand what you mean， and execute it in the database
`create view my_view as select * from idp_user group by mobile;`  
Then I went to the browser and request:    **http://idptest.cacov.cn/api/records/my_view**
The returned result is 9999. I want to know which of my steps is wrong

**Comment by lcuis** [comment] 2020-02-21 08:42
Hello @zhao666888 ,

Does the following query execute without error?
```SQL
select * from idp_user group by mobile
```
Because if there are other columns than `mobile` in your table, you will have to either add them in the grouping or aggregate them through another way such as for example `sum`, `avg`, etc: https://www.w3resource.com/mysql/aggregate-functions-and-grouping/aggregate-functions-and-grouping-in-mysql.php

**Comment by mevdschee** [comment] 2020-04-04 19:27
duplicate of #634?

**Comment by mevdschee** [comment] 2020-04-04 19:27
From #593:

>This helped:
>In this method: GenericDb::getOptions()
>set the option: 
>    \PDO::ATTR_EMULATE_PREPARES => true, // was false before

**Comment by pwFoo** [comment] 2020-04-05 08:45
Should be added to documentation? More solution and syntax examples would be great!

**Comment by mevdschee** [comment] 2020-04-06 15:48
@pwFoo, I am not sure, as emulated prepares are not recommended and I think the server is misconfigured, causing this error.

**Comment by mevdschee** [comment] 2020-04-22 00:03
>Should be added to documentation? More solution and syntax examples would be great!

Yes, please. A PR to the repository with documentation improvements and/or extra examples would be highly appreciated!

**Comment by mevdschee** [comment] 2020-09-30 10:13
Closing due to inactivity.

**Closed by mevdschee** 2020-09-30 10:13 UTC
Labels: help wanted

**Comment by mevdschee** [comment] 2021-03-03 18:22
Heads up that in v2.10.1 onwards the setting PDO::ATTR_EMULATE_PREPARES is no longer false and thus no need to workaround by increasing the `table_definition_cache`.
