### ISSUE TITLE
Additional SQL queries in authorization handlers

### ISSUE THREAD

**Issue by scriptPilot** [mevdschee/php-crud-api#1026] opened 2024-03-17 16:59 UTC
Is there any documentation how to perform additional SQL queries within authorization handlers?

**Comment by prof5alil** [comment] 2024-03-18 05:08
Hello,

I'm currently exploring the PHP CRUD API, and I'm excited about the possibility of using its features directly in other PHP files without relying on URL requests. I'm not very experienced in PHP coding, particularly with Object-Oriented Programming. I'd like to be able to pass a simple string, such as ("get", "records/users/1?exclude,password"), to a function and receive the response in JSON format. Could you please explain how to handle connection and closing the database connection, as well as how to perform CRUD operations in external PHP files?

I'm unsure if I'm using the right tool here, or if there are better alternatives available. At the moment, I'm considering using api.php because I'm already familiar with the PHP CRUD API (passing queries through URLs) and I'm thinking of utilizing api.php in this manner to reduce the amount of code in my project.

A big thanks for creating such a fantastic tool.

Cheers,

**Comment by mevdschee** [comment] 2024-03-19 08:19
Seems like a duplicate of #919

**Closed** 2024-03-19 09:53 UTC
Labels: help wanted

**Comment by scriptPilot** [comment] 2024-03-19 20:15
Thanks, I will follow the the descriptions :-)
