### ISSUE TITLE
Batch Insert

### ISSUE THREAD

**Issue by sthefaine** [mevdschee/php-crud-api#24] opened 2016-02-18 18:02 UTC
Hi,
Question is there a way to have this API code read a JSON Post that has more than level.
If I POST with just the first set all works.  If I try it with 2 it errors out.  I also tried to put [] around the JSON and changed the php code to not look for { but [ instead and set json_decode to true but I am stuck.  Any insight would be appreciated.  Thank You
Eample JSON : {
            "location": "Heart Place",
            "address": "4375 Booth Calloway",
            "address2": "Suite 4000",
            "city": "N Richland Hills",
            "state": "TX",
            "zip": "76180",
            "BTN": "8175902593",
            "customerreference": null,
            "apikey": "12345"},
   {
    "location": "Atlanta Office",
	"address": "3800 Arco Corporate Drive",
	"address2": "Suite 310",
	"city": "Atlanta",
	"state": "GA",
	"zip": "28226",
	"BTN": "7043237471",
   "customerreference": "12345",
   "apikey": "12345"
   }

**Comment by mevdschee** [comment] 2016-02-18 18:32
Batch insert is currently not supported and there are no plans to add it as HTTP2 will be here soon.

**Comment by mevdschee** [comment] 2016-03-09 14:56
duplicate of #3

**Closed by mevdschee** 2016-03-09 14:56 UTC
Labels: enhancement
