### ISSUE TITLE
Support for React Admin

### ISSUE THREAD

**Issue by nkappler** [mevdschee/php-crud-api#768] opened 2021-03-14 22:18 UTC
Hi,
I am trying to get this to work with react-admin: https://marmelab.com/react-admin/DataProviders.html#usage

However, the Content-Range header is missing in the HTTP Response. The simple REST data provider expects responses for lists of resources to contain this header with the total number of results to build the pagination.

Any help is hugely appreciated.

**Comment by mevdschee** [comment] 2021-03-15 19:44
Both the requests and the responses seem not to match the default Data Provider behavior. What is needed is a custom Data Provider implementation comparable to:

https://github.com/marmelab/react-admin/tree/master/packages/ra-data-json-server

I can start a repo for this if you are interested.

**Comment by mevdschee** [comment] 2021-03-15 20:05
Technically this is a duplicate of #613

**Comment by mevdschee** [comment] 2021-03-17 21:41
Does anyone want to give the dataprovider a shot and provide me with feedback?

**Comment by nkappler** [comment] 2021-03-18 09:40
Hi Maurits, 
thanks for your fast response and for implementing a Data Provider.
I was busy in the last days but I will test it in the evening!

**Comment by mevdschee** [comment] 2021-03-18 09:41
It is not ready/perfect for sure, but maybe you can help make it better.

**Comment by nkappler** [comment] 2021-03-18 09:49
I have already read through the code and it looks promising.
I had tried writing my own data provider as well and found a few similarities in yours,
but I am new to both react-admin and php-crud-api, hence my implementation was much less ready/perfect 😄 

Also, I don't have a large database at the moment, I am building that from scratch as well, so progress might be on the slower side...
Nonetheless, huge thanks for your help!

**Comment by nkappler** [comment] 2021-03-18 22:52
Ok, so I've had a bit if time for some basic testing.
Fetching records and pagination seems to work fine, however react-admin seems to always expect any update to return the modified record, whereas php-crud-api only returns the number of changed rows.

I have fixed it for now by sending another GET request after the PUT request, then it works without errors.

Is there a possibility to configure the api in a way that it returns the changed records? It would be nice to boil this down to one request.

If you tell me how to do it, I can implement it myself.
I then woul continue by collecting a few improvements in the next days and open a PR @mevdschee/ra-data-treeql/

**Comment by nkappler** [comment] 2021-03-18 22:59
Another issue I found is when listing records of an empty table, the api result doesn't include the `results` property, even when the  `page` parameter is set. I would expect it to return `0`.
Is this a bug?

**Comment by mevdschee** [comment] 2021-03-18 23:01
>I have fixed it for now by sending another GET request after the PUT request, then it works without errors.

Sounds as what I would have done

>Is there a possibility to configure the api in a way that it returns the changed records?

No not really.

>Another issue I found is when listing records of an empty table, the api result doesn't include the results property, even when the page parameter is set. I would expect it to return 0.

Yes you can argue that that is unexpected and therefor a bug. Feel free to open it. I'll see what I can do.

**Comment by mevdschee** [comment] 2021-03-18 23:03
> I then woul continue by collecting a few improvements in the next days and open a PR @mevdschee/ra-data-treeql/

I would be very happy to merge it :-)

**Comment by nkappler** [comment] 2021-03-18 23:21
> Feel free to open it. I'll see what I can do.

#772

Thanks again for your fast response. I am slowly getting suspicious about you being a robot, since your replies are a matter of minutes... :rofl:

**Closed** 2021-04-13 20:10 UTC
Labels: enhancement
