### ISSUE TITLE
NoSQL database support

### ISSUE THREAD

**Issue by Giuffre** [mevdschee/php-crud-api#272] opened 2017-06-27 15:55 UTC
Is it possible with `DatabaseInterface` to add the support to the most important NoSQL databases? e.g. MongoDB?

**Comment by Elemb** [comment] 2017-09-19 22:28
nothing is impossible.. the code is not too long to make modifies in..

**Comment by mevdschee** [comment] 2018-05-22 00:05
Duplicate of #280

**Closed by mevdschee** 2018-05-22 00:05 UTC
Labels: enhancement
