### ISSUE TITLE
Error 500 while doing a post request

### ISSUE THREAD

**Issue by nourz02** [mevdschee/php-crud-api#526] opened 2019-04-09 06:53 UTC
Hello,

I have a problem while executing a POST request. Here is what my request looks like :
`
const dette = {"id_user":233,"created_dt":"2019-04-09","amount":10,"commentaire":"test","paid":0,"modified_dt":"2019-04-09"}`

```
 fetch('https://www.mydomain.com/api/api.php/records/v2_dettes', {
      method: 'POST',
      body: dette
    })
      .then(() => {})
      .catch(error => {
        console.log(error);
      });
  };
```

Here is my table : https://screenshots.firefox.com/DhddAg9g0i9gOZHL/phpmyadmin.ovh.net

And what the request respond to me : 
`{"code":9999,"message":"Call to a member function execute() on boolean"}`

GET,UPDATE and DELETE are working like a charm.
But with the POST request, the api return me an internal error 500 but my record is present in the database !
Do you have any ideas why the api is raising me this error ?

Thanks in advance

**Comment by thipages** [comment] 2019-04-09 07:07
Hi,
[tinyint(1) is mapped with boolean](https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2622)
If you change "paid":0 to "paid":false, it might work

**Comment by mevdschee** [comment] 2019-04-09 08:03
@thipages Good suggestion!

**Comment by nourz02** [comment] 2019-04-09 08:03
First, thanks for you response

When using "paid': false, i got : 
`{"code":9999,"message":"SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'paid' at row 1"}`

So 1/0 seems to be the right way to pass the value.

**Comment by mevdschee** [comment] 2019-04-09 08:07
It could very well be a bug, but I would need to reproduce it locally before I can fix it. Does it happen on any tinyint(1)?

**Comment by nourz02** [comment] 2019-04-09 08:13
I only have one in my db structure.
If it's a bugm I can't help you on that because of my poor php skills.

**Comment by mevdschee** [comment] 2019-04-12 08:08
I was not able to reproduce the issue yet, although I have created the same table: 

    CREATE TABLE `v2_dettes` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `id_user` int(11) NOT NULL,
    `created_dt` date NOT NULL,
    `modified_dt` date NOT NULL,
    `amount` decimal(10,0) NOT NULL,
    `commentaire` varchar(255) CHARACTER SET utf8 NOT NULL,
    `paid` tinyint(1) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `id_user` (`id_user`),
    CONSTRAINT `v2_dettes_ibfk_1` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

Then doing:

    curl --data '{"id_user":2,"created_dt":"2019-04-09","amount":10,"commentaire":"test","paid":0,"modified_dt":"2019-04-09"}' http://localhost:8000/api.php/records/v2_dettes

resulted in:

    INSERT INTO `v2_dettes` (`id`, `id_user`, `created_dt`, `modified_dt`, `amount`, `commentaire`, `paid`) VALUES
    (2,	2,	'2019-04-09',	'2019-04-09',	10,	'test',	0);

So there must be something else different in your setup. Can you check (and post) the response headers (and make sure the "debug" config parameter is set to "true")?

**Comment by nourz02** [comment] 2019-04-12 08:24
Thanks for the follow up !
Indeed, your setup seems the same.

Here is the response header with the debug true : 

> HTTP/1.1 500 Internal Server Error
Set-Cookie: 60gp=R4109521858; path=/; expires=Fri, 12-Apr-2019 09:26:46 GMT
Date: Fri, 12 Apr 2019 08:19:28 GMT
Server: Apache
X-Powered-By: PHP/7.2
Content-Length: 72
X-Exception-Message: Call to a member function execute() on boolean
X-Exception-File: /home/odsladqg/www/api/api.php:2015
Content-Type: application/json
X-IPLB-Instance: 504

https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2015

I tried through a browser and directly with curl. Same result.

**Comment by mevdschee** [comment] 2019-04-12 08:47
Can you add this to line 2014:

    var_dump($sql);
      
Hopefuly it will help us to find why the prepare statement is failing.

**Comment by nourz02** [comment] 2019-04-12 09:13
I don't know why, but the response is not complete.

Response raw:
`string(113) "INSERT INTO "v2_dettes" ("id_user","created_dt","modified_dt"`

Response header:

> content-length →74
content-type →application/json
date →Fri, 12 Apr 2019 09:09:35 GMT
server →Apache
x-exception-file →/home/odsladqg/www/api/api.php:2016
x-exception-message →Call to a member function errorInfo() on boolean
x-iplb-instance →17329
x-powered-by →PHP/7.2

Maybe I can send you the url of my api by mail ?

**Comment by mevdschee** [comment] 2019-04-12 09:17
Comment out this line on line 5834:

    $this->addHeader('Content-Length', strlen($data));

Then change the second debug statement to:

    var_dump($this->pdo->errorInfo());

Let's see whether or not that helps.

>Maybe I can send you the url of my api by mail ?

Sure, but sending the URL by email is not helping me much.

**Comment by nourz02** [comment] 2019-04-12 09:23
> string(113) "INSERT INTO "v2_dettes" ("id_user","created_dt","modified_dt","amount","commentaire","paid") VALUES (?,?,?,?,?,?)"
> array(3) {
>   [0]=>
>   string(5) "00000"
>   [1]=>
>   NULL
>   [2]=>
>   NULL
> }
> string(23) "SELECT LAST_INSERT_ID()"
> array(3) {
>   [0]=>
>   string(5) "00000"
>   [1]=>
>   NULL
>   [2]=>
>   NULL
> }
> {"code":9999,"message":"Call to a member function execute() on boolean"}

**Comment by mevdschee** [comment] 2019-04-12 09:35
It is very strange, but the prepare call returns a boolean, while it should throw an error, due to this line on line 1809:

    \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,

Is that still there?

**Comment by nourz02** [comment] 2019-04-12 09:47
Yes. I changed nothing excepts credentials and the middleware cors in the api.php

**Comment by mevdschee** [comment] 2019-04-12 09:52
All I can think of is that you (or your user) only has read permissions in the database. Could this be the case? Can you try to manually insert some values?

**Comment by nourz02** [comment] 2019-04-12 11:28
```
 1 row inserted.
Inserted row id: 469 (Query took 0.0004 seconds.)
INSERT INTO `v2_dettes` (`id_user`, `created_dt`, `modified_dt`, `amount`, `commentaire`, `paid`) VALUES (223, '2019-04-09', '2019-04-09', 10, 'test', 0) 
```

But remember that the POST to the api is working (the row is added to the db) but it's just that the API raise me an error !
My app using the api is working, but I need to ignore the error given by the api.

**Comment by mevdschee** [comment] 2019-04-12 11:33
Well.. you could add an `@` in front of the offending line :-)

**Comment by mevdschee** [comment] 2019-04-12 17:24
I would not know how to reproduce. Can you help me?

**Comment by mevdschee** [comment] 2019-04-17 07:12
I rarely give up on an error, but this one is particularly hard to reproduce.

I have read somewhere that somebody said that prepare may return false in some occasions:

>turns out that one of my field names was incorrect

Maybe you should recheck the query for non-visible characters that are copy pasted in?

I have really out of ideas. Can you help me or did you solve it already?

**Comment by nourz02** [comment] 2019-04-17 08:34
Hello,

Sorry I'm a little bit out of time atm.
I will double check for invisible characters as soon as possible.
Thanks for you help !

**Comment by mevdschee** [comment] 2019-04-22 21:37
I'm closing this issue for now. Feel free to report new insights.

**Closed by mevdschee** 2019-04-22 21:37 UTC
Labels: bug, invalid
