### ISSUE TITLE
Handle multiple create error

### ISSUE THREAD

**Issue by khalid-o** [mevdschee/php-crud-api#744] opened 2021-01-25 19:40 UTC
Hi there,
Could you help me with an issue. 
When creating multiple resource at once (three for example), and one of them throw an exception such as "Duplicate key exception", I can't resume the operation because of two things: 
1- I don't know which one get me this error.
2- If any one of them succeeded, throw same error next time.

Thank you.

**Comment by mevdschee** [comment] 2021-01-26 15:20
Hi, Thank you for opening this issue. Batch operations are transactions and will be rolled back. Doing them one-by-one afterwards may help you solve your problem. Kind regards, Maurits

**Comment by khalid-o** [comment] 2021-01-26 15:36
Thank you for your help.
But I think batch create operation is not transactional, because some of them saved in database.

**Comment by mevdschee** [comment] 2021-01-27 08:08
This must be a regression then, not covered by a test case. I will add a test case now and then fix this bug.

**Comment by khalid-o** [comment] 2021-01-27 14:13
Thank you

**Comment by mevdschee** [comment] 2021-01-28 07:19
Please review the test cases and the new behavior.

**Comment by khalid-o** [comment] 2021-01-28 10:01
I will, Thank you

**Comment by mevdschee** [comment] 2021-01-28 10:03
I'm working on improving it a bit more, as I would not expect "200 OK" response status on a rolled back transaction.

**Comment by khalid-o** [comment] 2021-01-28 10:10
I reviewed test cases, are they rollback all request, and didn't create any of sent resource, correct?

**Comment by mevdschee** [comment] 2021-01-28 10:15
Can you pull and retry? You should see error documents and a "424" (failed dependency) status code.

**Comment by mevdschee** [comment] 2021-01-28 10:24
I think it is good like this. I'll update the README to reflect the improved behavior.

**Comment by mevdschee** [comment] 2021-01-28 10:47
I updated the README and improved the error reporting even more.

**Comment by mevdschee** [comment] 2021-01-28 11:06
Relevant section of the readme:

And the return values are the number of rows that are set:

    [1,1]

Which means that there were two update operations and each of them had set one row. Batch operations use database
transactions, so they either all succeed or all fail (successful ones get roled back). If they fail the body will
contain the list of error documents. In the following response the first operation succeeded and the second operation
of the batch failed due to an integrity violation:

    [   
        {
            "code": 0,
            "message": "Success"
        },
        {
            "code": 1010,
            "message": "Data integrity violation"
        }
    ]

The response status code will always be 424 (failed dependency) in case of failure of one of the batch operations.

**Comment by khalid-o** [comment] 2021-01-28 11:36
I think this is almost perfect, amazing work, but do you think the 422 status is more accurate?

**Comment by khalid-o** [comment] 2021-01-28 11:37
But overall this is a good improvement. Great work.

**Comment by mevdschee** [comment] 2021-01-28 12:09
>I think this is almost perfect,

What would you improve?

**Comment by khalid-o** [comment] 2021-01-28 12:11
> > I think this is almost perfect,
> 
> What would you improve?

What do you mean?

**Comment by mevdschee** [comment] 2021-01-28 12:12
>What do you mean?

What would you want different, and how?

**Comment by khalid-o** [comment] 2021-01-28 12:13
> What would you want different, and how?

No no, I didn't mean that, I mean nothing is perfect, but your work has come close <3.

**Comment by mevdschee** [comment] 2021-01-28 12:15
Okay.. in that case.. I'll close this issue and release a new version. Thank you for your contribution. I really appreciate your collaboration and the improvement (bugfix) we did together. Kind regards, Maurits

**Closed by mevdschee** 2021-01-28 12:15 UTC
Labels: bug

**Comment by mevdschee** [comment] 2021-01-28 12:19
FYI, v2.9.36 "Bugfix batch errors" has been released, containing this fix.
