### ISSUE TITLE
geojson no table issue

### ISSUE THREAD

**Issue by ano** [mevdschee/php-crud-api#577] opened 2019-09-22 04:52 UTC
When using **/records/**
```json
{
"records": [
{
"FFA_VID": 4226,
"VESSEL_NAME": "MARORAOI",
"IRCS": "T3LN2",
"FLAG": "KI",
"DATE": "2015-01-01",
"LAT": -4.687305625,
"LON": 184.1413055,
"STATUS": "NORMAL",
"SOURCE": "FFA_RSP_DAILY_AVG",
"VESSEL_TYPE": "SINGLE PURSE SEINE",
"POSITION": "POINT(-4.687305625 184.1413055)"
},

```
However, if I switch to use **/geojson/** feature I get
```json
{
"code": 1001,
"message": "Table 'vessel_position' not found"
}
```
Am I missing something?

**Comment by mevdschee** [comment] 2019-09-22 17:44
Thank you for reaching out. What is the type of the POSITION field?

**Comment by ano** [comment] 2019-09-22 21:05
It's a **point** data type from a MariaDB database

**Comment by mevdschee** [comment] 2019-09-22 23:16
I can't reproduce. Can you isolate the problem for me?

**Comment by mevdschee** [comment] 2019-09-25 07:22
The test in `tests/functional/001_records/083_list_users_as_geojson.log` is testing this functionality. Is it failing for you?

**Comment by mevdschee** [comment] 2019-09-25 07:23
Run `php test.php mysql 001` to execute all tests to see whether or not it works.

**Comment by mevdschee** [comment] 2019-09-30 17:45
Any update?

**Comment by ano** [comment] 2019-10-03 09:09
I’ll try reproduce it in my local environment, I don’t have command line access with the hosting provider I use

**Comment by mevdschee** [comment] 2019-10-16 22:26
Any update?

**Comment by ano** [comment] 2019-10-17 13:26
My hosting provider doesn’t allow cli access so I’ll try run the tests on the local environment and get back to you on this. As well as try to replicate the error.

**Comment by mevdschee** [comment] 2019-10-28 14:01
Closing for now, I'll re-open when you have more information

**Closed by mevdschee** 2019-10-28 14:01 UTC
Labels: help wanted

**Comment by ano** [comment] 2019-11-09 07:35
Sorry for the late reply, I fixed the issue by setting **authorisation.tableHandler** as follows

```PHP        
'authorization.tableHandler' => function ($operation, $tableName) {                
            return (in_array($operation,array('list','read','document','unknown')));        
        }
```
So for my use case the full **config** is as follows for anyone else having the same issues with getting geojson working

```PHP
    $config = new Config([
        'username' => "root",
        'password' => "",
        'database' => "vessel_positions",
        'address' => "localhost",
        'port' => "3306",
        'controllers' => "records,geojson,openapi",
        'middlewares' => "authorization",
        'openApiBase' => '{"info":{"title":"Vessel Positions","version":"1.0.0"}}',
        'authorization.tableHandler' => function ($operation, $tableName) {                
            return (in_array($operation,array('list','read','document','unknown')));        
        }    
    ]);
```

**Comment by mevdschee** [comment] 2019-11-09 17:36
Thank you, I have fixed this.
