### ISSUE TITLE
PostgreSQL specific issues

### ISSUE THREAD

**Issue by rrjanbiah** [mevdschee/php-crud-api#149] opened 2016-12-09 14:42 UTC
Looks mostly like PostgreSQL specific issues (not sure about other databases though)

- `table_comment` related issue as in #68 
```
Warning: pg_query(): Query failed: ERROR:  column "table_comment" does not exist LINE 2:      "table_name","table_comment" ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368
```
- `relation` related query errors
```
Warning: pg_query(): Query failed: ERROR: relation "attributes" does not exist LINE 1: SELECT * FROM "attributes" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "character_sets" does not exist LINE 1: SELECT * FROM "character_sets" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "check_constraint_routine_usage" does not exist LINE 1: SELECT * FROM "check_constraint_routine_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "information_schema_catalog_name" does not exist LINE 1: SELECT * FROM "information_schema_catalog_name" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "applicable_roles" does not exist LINE 1: SELECT * FROM "applicable_roles" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "administrable_role_authorizations" does not exist LINE 1: SELECT * FROM "administrable_role_authorizations" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "check_constraints" does not exist LINE 1: SELECT * FROM "check_constraints" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "collations" does not exist LINE 1: SELECT * FROM "collations" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "collation_character_set_applicability" does not exist LINE 1: SELECT * FROM "collation_character_set_applicability" WHERE ... ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "column_domain_usage" does not exist LINE 1: SELECT * FROM "column_domain_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "column_privileges" does not exist LINE 1: SELECT * FROM "column_privileges" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "column_udt_usage" does not exist LINE 1: SELECT * FROM "column_udt_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "columns" does not exist LINE 1: SELECT * FROM "columns" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "constraint_column_usage" does not exist LINE 1: SELECT * FROM "constraint_column_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "constraint_table_usage" does not exist LINE 1: SELECT * FROM "constraint_table_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "domain_constraints" does not exist LINE 1: SELECT * FROM "domain_constraints" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "domain_udt_usage" does not exist LINE 1: SELECT * FROM "domain_udt_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "domains" does not exist LINE 1: SELECT * FROM "domains" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "enabled_roles" does not exist LINE 1: SELECT * FROM "enabled_roles" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "key_column_usage" does not exist LINE 1: SELECT * FROM "key_column_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "parameters" does not exist LINE 1: SELECT * FROM "parameters" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "referential_constraints" does not exist LINE 1: SELECT * FROM "referential_constraints" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "role_column_grants" does not exist LINE 1: SELECT * FROM "role_column_grants" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "routine_privileges" does not exist LINE 1: SELECT * FROM "routine_privileges" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "role_routine_grants" does not exist LINE 1: SELECT * FROM "role_routine_grants" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "routines" does not exist LINE 1: SELECT * FROM "routines" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "schemata" does not exist LINE 1: SELECT * FROM "schemata" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sequences" does not exist LINE 1: SELECT * FROM "sequences" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sql_features" does not exist LINE 1: SELECT * FROM "sql_features" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sql_implementation_info" does not exist LINE 1: SELECT * FROM "sql_implementation_info" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sql_languages" does not exist LINE 1: SELECT * FROM "sql_languages" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sql_packages" does not exist LINE 1: SELECT * FROM "sql_packages" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sql_parts" does not exist LINE 1: SELECT * FROM "sql_parts" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sql_sizing" does not exist LINE 1: SELECT * FROM "sql_sizing" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "sql_sizing_profiles" does not exist LINE 1: SELECT * FROM "sql_sizing_profiles" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "table_constraints" does not exist LINE 1: SELECT * FROM "table_constraints" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "table_privileges" does not exist LINE 1: SELECT * FROM "table_privileges" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "role_table_grants" does not exist LINE 1: SELECT * FROM "role_table_grants" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "tables" does not exist LINE 1: SELECT * FROM "tables" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "transforms" does not exist LINE 1: SELECT * FROM "transforms" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "triggered_update_columns" does not exist LINE 1: SELECT * FROM "triggered_update_columns" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "triggers" does not exist LINE 1: SELECT * FROM "triggers" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "udt_privileges" does not exist LINE 1: SELECT * FROM "udt_privileges" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "role_udt_grants" does not exist LINE 1: SELECT * FROM "role_udt_grants" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "usage_privileges" does not exist LINE 1: SELECT * FROM "usage_privileges" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "role_usage_grants" does not exist LINE 1: SELECT * FROM "role_usage_grants" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "user_defined_types" does not exist LINE 1: SELECT * FROM "user_defined_types" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "view_column_usage" does not exist LINE 1: SELECT * FROM "view_column_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "view_routine_usage" does not exist LINE 1: SELECT * FROM "view_routine_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "view_table_usage" does not exist LINE 1: SELECT * FROM "view_table_usage" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "views" does not exist LINE 1: SELECT * FROM "views" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "data_type_privileges" does not exist LINE 1: SELECT * FROM "data_type_privileges" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "element_types" does not exist LINE 1: SELECT * FROM "element_types" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "_pg_foreign_table_columns" does not exist LINE 1: SELECT * FROM "_pg_foreign_table_columns" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "column_options" does not exist LINE 1: SELECT * FROM "column_options" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "_pg_foreign_data_wrappers" does not exist LINE 1: SELECT * FROM "_pg_foreign_data_wrappers" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "foreign_data_wrapper_options" does not exist LINE 1: SELECT * FROM "foreign_data_wrapper_options" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "foreign_data_wrappers" does not exist LINE 1: SELECT * FROM "foreign_data_wrappers" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "_pg_foreign_servers" does not exist LINE 1: SELECT * FROM "_pg_foreign_servers" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "foreign_server_options" does not exist LINE 1: SELECT * FROM "foreign_server_options" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "foreign_servers" does not exist LINE 1: SELECT * FROM "foreign_servers" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "_pg_foreign_tables" does not exist LINE 1: SELECT * FROM "_pg_foreign_tables" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "foreign_table_options" does not exist LINE 1: SELECT * FROM "foreign_table_options" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "foreign_tables" does not exist LINE 1: SELECT * FROM "foreign_tables" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "_pg_user_mappings" does not exist LINE 1: SELECT * FROM "_pg_user_mappings" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "user_mapping_options" does not exist LINE 1: SELECT * FROM "user_mapping_options" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368

Warning: pg_query(): Query failed: ERROR: relation "user_mappings" does not exist LINE 1: SELECT * FROM "user_mappings" WHERE 1=2; ^ in D:\xampp1\htdocs\php-crud-api\api.php on line 368
```
- `pg_` tables are exposed in Swagger doc
```
{"name":"pg_statistic","description":""},{"name":"pg_type","description":""},{"name":"pg_authid","description":""},{"name":"pg_roles","description":""},{"name":"pg_shadow","description":""},{"name":"pg_group","description":""},{"name":"pg_user","description":""},{"name":"pg_policies","description":""},{"name":"pg_settings","description":""},{"name":"pg_rules","description":""},{"name":"pg_file_settings","description":""},{"name":"pg_views","description":""},{"name":"pg_tables","description":""},{"name":"pg_matviews","description":""},{"name":"pg_indexes","description":""},{"name":"pg_stats","description":""},{"name":"pg_locks","description":""},{"name":"pg_cursors","description":""},{"name":"pg_available_extensions","description":""},{"name":"pg_available_extension_versions","description":""},{"name":"pg_prepared_xacts","description":""},{"name":"pg_prepared_statements","description":""},{"name":"pg_seclabels","description":""},{"name":"pg_timezone_abbrevs","description":""},{"name":"pg_timezone_names","description":""},{"name":"pg_stat_all_tables","description":""},{"name":"pg_stat_xact_all_tables","description":""},{"name":"pg_stat_sys_tables","description":""},{"name":"pg_stat_user_tables","description":""},{"name":"pg_stat_xact_user_tables","description":""},{"name":"pg_statio_all_tables","description":""},{"name":"pg_statio_sys_tables","description":""},{"name":"pg_statio_user_tables","description":""},{"name":"pg_stat_all_indexes","description":""},{"name":"pg_stat_sys_indexes","description":""},{"name":"pg_stat_user_indexes","description":""},{"name":"pg_statio_all_indexes","description":""},{"name":"pg_statio_sys_indexes","description":""},{"name":"pg_statio_user_indexes","description":""},{"name":"pg_statio_all_sequences","description":""},{"name":"pg_statio_sys_sequences","description":""},{"name":"pg_statio_user_sequences","description":""},{"name":"pg_stat_activity","description":""},{"name":"pg_stat_replication","description":""},{"name":"pg_stat_ssl","description":""},{"name":"pg_replication_slots","description":""},{"name":"pg_stat_database","description":""},{"name":"pg_user_mapping","description":""},{"name":"pg_stat_bgwriter","description":""},{"name":"pg_replication_origin_status","description":""},{"name":"pg_user_mappings","description":""},{"name":"pg_largeobject","description":""},{"name":"pg_attribute","description":""},{"name":"pg_proc","description":""},{"name":"pg_class","description":""},{"name":"pg_attrdef","description":""},{"name":"pg_constraint","description":""},{"name":"pg_inherits","description":""},{"name":"pg_index","description":""},{"name":"pg_operator","description":""},{"name":"pg_opfamily","description":""},{"name":"pg_opclass","description":""},{"name":"pg_am","description":""},{"name":"pg_amop","description":""},{"name":"pg_amproc","description":""},{"name":"pg_language","description":""},{"name":"pg_largeobject_metadata","description":""},{"name":"pg_aggregate","description":""},{"name":"pg_rewrite","description":""},{"name":"pg_trigger","description":""},{"name":"pg_event_trigger","description":""},{"name":"pg_description","description":""},{"name":"pg_cast","description":""},{"name":"pg_enum","description":""},{"name":"pg_namespace","description":""},{"name":"pg_conversion","description":""},{"name":"pg_depend","description":""},{"name":"pg_db_role_setting","description":""},{"name":"pg_tablespace","description":""},{"name":"pg_pltemplate","description":""},{"name":"pg_auth_members","description":""},{"name":"pg_shdepend","description":""},{"name":"pg_shdescription","description":""},{"name":"pg_ts_config","description":""},{"name":"pg_ts_config_map","description":""},{"name":"pg_ts_dict","description":""},{"name":"pg_ts_parser","description":""},{"name":"pg_ts_template","description":""},{"name":"pg_extension","description":""},{"name":"pg_foreign_data_wrapper","description":""},{"name":"pg_foreign_server","description":""},{"name":"pg_foreign_table","description":""},{"name":"pg_policy","description":""},{"name":"pg_replication_origin","description":""},{"name":"pg_default_acl","description":""},{"name":"pg_seclabel","description":""},{"name":"pg_shseclabel","description":""},{"name":"pg_collation","description":""},{"name":"pg_range","description":""},{"name":"pg_transform","description":""},{"name":"pg_stat_xact_sys_tables","description":""},{"name":"pg_stat_database_conflicts","description":""},{"name":"pg_stat_user_functions","description":""},{"name":"pg_stat_xact_user_functions","description":""},{"name":"pg_stat_archiver","description":""},{"name":"pg_database","description":""}
```
- Swagger doc json is not compliant with https://github.com/swagger-api/swagger-ui for `POST`

It doesn't hint `application/x-www-form-urlencoded` and so Swagger UI generates JSON body and so it fails.
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \     "name": "test", \     "icon": "test-icon" \   }' 'http://localhost/php-crud-api/api.php/categories'
```
- Suggestion: Log SQL errors https://github.com/mevdschee/php-crud-api/blob/master/api.php#L368 Disabling errors with `@` makes debugging difficult

If possible, please provide some guideline or hint to fix these issues and I'll try to provide PR.

**Comment by mevdschee** [comment] 2016-12-09 16:52
Hi, thank you for reaching out. Excellent report. Which version of postgresql are you running? 

>If possible, please provide some guideline or hint to fix these issues and we'll try to provide PR.

Can you first provide a failing test case? See the `tests` directory.

**Comment by mevdschee** [comment] 2016-12-09 17:25
I was not able to reproduce the first issue, did you use the (latest) version with the fix from #68?

**Comment by mevdschee** [comment] 2016-12-09 17:26
>It doesn't hint application/x-www-form-urlencoded and so Swagger UI generates JSON body and so it fails.

It shouldn't, as JSON body is correct input on POST. Can you provide replication steps?

**Comment by mevdschee** [comment] 2016-12-09 17:30
>Disabling errors with @ makes debugging difficult

These errors may be failing constraints, while other errors should not be reported to the user. We cannot decide, suppressing seems as the safest option. You can remove the '@' during debugging. We could make that a configuration option, in line with #14

**Comment by rrjanbiah** [comment] 2016-12-10 05:39
@mevdschee 

> I was not able to reproduce the first issue, did you use the (latest) version with the fix from #68?

#68 is for `SQLServer`. But, this ticket is about `PostgreSQL`. Or, am I missing something?

**Comment by mevdschee** [comment] 2016-12-11 10:32
>#68 is for SQLServer. But, this ticket is about PostgreSQL. Or, am I missing something?

Yeah, you are right, I was mistaken, but you still didn't answer the (relevant) question:

- Did you use the (latest) version?

I have asked you other questions in answers that you have not responded on:

- JSON body is correct input on POST. Can you provide replication steps?
- Can you first provide a failing test case? See the tests directory.

Further I would like to know:

- Which version of postgresql are you running?
- Which version of PHP are you running?
- Which Operating System are you running on?

It is hard to help you if you don't answer the questions.

**Comment by rrjanbiah** [comment] 2016-12-11 11:28
@mevdschee I'm away. Will reply in couple of days with relevant information

**Comment by mevdschee** [comment] 2016-12-15 00:16
@rrjanbiah any updates?

**Comment by mevdschee** [comment] 2016-12-16 08:05
Closing the bug for now until there are updates.

**Comment by rrjanbiah** [comment] 2016-12-16 15:32
@mevdschee Sorry for the delay. I'm still not actively back. Once I'm back, will provide more test cases. For now, just posting reply from other developers.. Will also open couple of issues to dump things in my mind.

> Did you use the latest version?

Yes

> Which version of postgresql are you running?

9.5.4

> It shouldn't (fail), as JSON body is correct input on POST. Can you provide replication steps?

1. Generate API document using php-crud-api (`blog_postgresql.sql`) and save as `swagger.json`
2. Download swagger-ui and place the `swagger.json` 
3. Go to http://localhost/swagger-ui/
4. Now when you try posting value in any tables, you can see the "Response Body" as `null
5. If you change @pg_query to pg_query and post, the "Response Body" as "no content"
6. But when we post in `Postman` via `application/x-www-form-urlencoded`, its working fine. 

> Which version of PHP are you running?

5.6.24

> Which Operating System are you running on?

Windows 10

**Comment by mevdschee** [comment] 2016-12-16 16:24
>Swagger doc json is not compliant with https://github.com/swagger-api/swagger-ui for POST

Maybe you should remove the backslashes from the input:

```
maurits@nuc:~$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"name":"test","icon":"test-icon"}' 'http://localhost:8000/blog.php/categories'
3
```

Goes fine (JSON is valid). 

```
maurits@nuc:~$curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \     "name": "test", \     "icon": "test-icon" \   }' 'http://localhost:8000/blog.php/categories'
Not found (input)
```

Fails on input, as the input contains illegal characters (backslashes).

**Comment by mevdschee** [comment] 2016-12-16 16:47
Most likely the script is outputting warnings, invalidating the JSON

**Comment by mevdschee** [comment] 2016-12-16 16:52
>pg_ tables are exposed in Swagger doc

The errors you are reporting may result from using a super user for application database access.

**Comment by mevdschee** [comment] 2016-12-16 17:06
After 7 days there still is no failing test case provided, and all of the reported problems (unfortunately multiple in this issue) seem invalid. Please open new issues if you want to continue, one per problem/suggestion and reference this issue.

**Closed by mevdschee** 2016-12-16 17:06 UTC
Labels: bug
