### ISSUE TITLE
error : preg_replace_callback(): Requires argument 2

### ISSUE THREAD

**Issue by rajurk2000** [mevdschee/php-crud-api#167] opened 2017-01-22 20:20 UTC
hi sir,

i am getting following error message in error.log file.

using MySQL database, refer attached api output.

PHP Warning:  preg_replace_callback(): Requires argument 2, '', to be a valid callback in /home/uponcje1/public_html/crud/api.php on line 139

![image](https://cloud.githubusercontent.com/assets/7404630/22185554/35820cf0-e10e-11e6-8aec-9deed8f06d04.png)

**Comment by mevdschee** [comment] 2017-01-22 22:02
Thank you for reaching out. I would love to help you, but I need some more information.

In the latest version line 139 does not contain a 'preg_replace_callback'. Can you also confirm that this issue is still happening in the latest version?

Also can you post the contents of line 139?

**Comment by rajurk2000** [comment] 2017-01-23 02:25
Dear sir,

Thanks for your prompt reply.

refer following details and screenshot.

this is the file/code I have downloaded yesterday so I don't have any other
version. If you have latest api code kind forward the same.




public function query($sql,$params=array()) {
$db = $this->db;
$sql = preg_replace_callback('/\!|\?/', function ($matches) use
(&$db,&$params) {
$param = array_shift($params);
if ($matches[0]=='!') {
$key = preg_replace('/[^a-zA-Z0-9\-_=<>
]/','',is_object($param)?$param->key:$param);
if (is_object($param) && $param->type=='base64') {
return "TO_BASE64(\"$key\") as \"$key\"";
}
if (is_object($param) && $param->type=='wkt') {
return "ST_AsText(\"$key\") as \"$key\"";
}
return '"'.$key.'"';
} else {
if (is_array($param)) return '('.implode(',',array_map(function($v) use
(&$db) {
return "'".mysqli_real_escape_string($db,$v)."'";
},$param)).')';
if (is_object($param) && $param->type=='base64') {
return "x'".bin2hex(base64_decode($param->value))."'";
}
if (is_object($param) && $param->type=='wkt') {
return
"ST_GeomFromText('".mysqli_real_escape_string($db,$param->value)."')";
}
if ($param===null) return 'NULL';
return "'".mysqli_real_escape_string($db,$param)."'";
}
}, $sql);
if (!strpos($sql,'INFORMATION_SCHEMA')) echo "\n$sql\n";
return mysqli_query($db,$sql);
}



[image: Inline image 1]




[image: Inline image 2]

**Comment by mevdschee** [comment] 2017-01-23 02:27
You are welcome. Unfortunately your email is not showing up properly on Github, please update it.

**Comment by rajurk2000** [comment] 2017-01-23 02:51
Dear sir,

Thanks for your prompt reply.

refer following details and screenshot.

this is the file/code I have downloaded yesterday so I don't have any other version. If you have latest api code kind forward the same.




public function query($sql,$params=array()) {
		$db = $this->db;
		$sql = preg_replace_callback('/\!|\?/', function ($matches) use (&$db,&$params) {
			$param = array_shift($params);
			if ($matches[0]=='!') {
				$key = preg_replace('/[^a-zA-Z0-9\-_=<> ]/','',is_object($param)?$param->key:$param);
				if (is_object($param) && $param->type=='base64') {
					return "TO_BASE64(\"$key\") as \"$key\"";
				}
				if (is_object($param) && $param->type=='wkt') {
					return "ST_AsText(\"$key\") as \"$key\"";
				}
				return '"'.$key.'"';
			} else {
				if (is_array($param)) return '('.implode(',',array_map(function($v) use (&$db) {
					return "'".mysqli_real_escape_string($db,$v)."'";
				},$param)).')';
				if (is_object($param) && $param->type=='base64') {
					return "x'".bin2hex(base64_decode($param->value))."'";
				}
				if (is_object($param) && $param->type=='wkt') {
					return "ST_GeomFromText('".mysqli_real_escape_string($db,$param->value)."')";
				}
				if ($param===null) return 'NULL';
				return "'".mysqli_real_escape_string($db,$param)."'";
			}
		}, $sql);
		if (!strpos($sql,'INFORMATION_SCHEMA'))	echo "\n$sql\n";
		return mysqli_query($db,$sql);
	}



![image](https://cloud.githubusercontent.com/assets/7404630/22189795/dd4448d2-e144-11e6-9b53-98c746228069.png)



![image](https://cloud.githubusercontent.com/assets/7404630/22189803/ecd9196c-e144-11e6-89ba-6d67140a0d8c.png)

**Comment by rajurk2000** [comment] 2017-01-23 17:16
Dear Sir,

as you advice i have commented line number 2 , after doing this i am getting out as per screen shot 2.

![image](https://cloud.githubusercontent.com/assets/7404630/22214464/ac5ed614-e1bd-11e6-9b05-4d0eee21d348.png)


![image](https://cloud.githubusercontent.com/assets/7404630/22214502/cb294dfe-e1bd-11e6-90bf-436f65930b33.png)

**Comment by mevdschee** [comment] 2017-01-23 18:18
And do you have a table named "employeemast"?

**Comment by rajurk2000** [comment] 2017-01-23 18:29
yes, table name is correct, but it has some records, refer below screen shot

![image](https://cloud.githubusercontent.com/assets/7404630/22217140/e4ffcd70-e1c7-11e6-90e6-58d276fb041c.png)

**Comment by mevdschee** [comment] 2017-01-23 18:31
You probably have defined a 'table_authorizer', because I can't see those tables in the swagger output. Can you post the definition of the 'table_authorizer' function?

**Comment by rajurk2000** [comment] 2017-01-23 18:53
i not expert in PHP, can you be more specific, where and what code i should write.

as i would be performing get , post & put functions.

pls. help me i need your support very badly.

**Comment by mevdschee** [comment] 2017-01-23 18:57
I think you may have not entered the configuration right in the bottom of the "api.php" file. Can you check that you have the "database", "username" and "password" fields set to the values you use to login to PHPMyAdmin?

**Comment by rajurk2000** [comment] 2017-01-23 19:26
Refer below credential updated, by using same credential i am able to get data using some other php file.
can you advice how to check whether i am connected to DB or not.

![image](https://cloud.githubusercontent.com/assets/7404630/22219199/e11e0d0e-e1cf-11e6-8f86-9719060c9287.png)

**Comment by mevdschee** [comment] 2017-01-23 19:31
Maybe you are not allowed to do 'information_schema' queries. Can you try to execute the following SQL from PHPMyAdmin?

    SELECT `TABLE_NAME`,`TABLE_COMMENT` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA` = 'uponcje1_eappsupon';

Please post the output.

**Comment by rajurk2000** [comment] 2017-01-23 19:39
refer below output and user privileges.

![image](https://cloud.githubusercontent.com/assets/7404630/22219626/87d7e89e-e1d1-11e6-9d96-abc722c19f5f.png)


![image](https://cloud.githubusercontent.com/assets/7404630/22219674/b44c5d56-e1d1-11e6-8909-e5362903607c.png)

**Comment by mevdschee** [comment] 2017-01-23 19:45
Can you add:

    echo "\n$sql\n";

after line 140 and post the output at:

    http://upon.co.in/crud/api.php/

I think your queries are somehow failing.

**Comment by mevdschee** [comment] 2017-01-23 19:47
Additional questions: What version is your database? Is the "mysqli" (note the 'i') extension enabled?

**Comment by rajurk2000** [comment] 2017-01-23 20:00
no it is MySql only. if you want you can connect my laptop using remote software like teamviewer-10
id : 797 766 552 pw: 5104

![image](https://cloud.githubusercontent.com/assets/7404630/22220370/6cddabd4-e1d4-11e6-9517-0adcff055307.png)

**Comment by rajurk2000** [comment] 2017-01-23 20:15
refer below output after adding echo "\n$sql\n"; at line 140


![image](https://cloud.githubusercontent.com/assets/7404630/22220897/a17d7372-e1d6-11e6-94a2-ef0d7f2bb3c8.png)

**Comment by mevdschee** [comment] 2017-01-23 20:32
It seems you run percona mysql 5.5.44, let me check whether or not I can make it work on that version. Please hold on..

**Comment by rajurk2000** [comment] 2017-01-23 20:54
thx for your great support and prompt action, i would be very thankful, if you can make it.

thx.....

**Comment by mevdschee** [comment] 2017-01-23 21:05
It is hard to reproduce your problem. I installed percona 5.5.53 and it works. There are some issues:

- no spatial support
- no utf8mb4 support
- no datetime(3) support

Are you sure the credentials work properly and these are for the right database? Do you have an error log in cpanel where something can be seen?

**Comment by rajurk2000** [comment] 2017-01-24 02:31
Using same credentials I am getting day for http://upon.co.in/service.php/
empmast

On Jan 24, 2017 2:35 AM, "Maurits van der Schee" <notifications@github.com>
wrote:

[image: Inline image 1]

**Comment by mevdschee** [comment] 2017-01-24 08:02
No error log entries? Can you install Adminer and try the information schema query using the credentials you use for service.php? See https://Adminer.org it is a single file phpmyadmin alternative.

**Comment by rajurk2000** [comment] 2017-01-24 13:00
no, there is no error log.

sure will try and let you know the outcome. thx for your support.

**Comment by mevdschee** [comment] 2017-01-24 18:58
>no, there is no error log

I think there is, you said earlier:

>i am getting following error message in error.log file.

Can you post the full contents of the error.log file (or mail it to me?)

**Comment by rajurk2000** [comment] 2017-01-24 19:08
refer below screen shot, i am able to connect with same credential using adminer-4.2.5-mysql tool.

also refer attached log file

![image](https://cloud.githubusercontent.com/assets/7404630/22262225/13661d6c-e296-11e6-96b1-3b2a3d1a873c.png)


![image](https://cloud.githubusercontent.com/assets/7404630/22262215/03e4fb1a-e296-11e6-8fa5-979751c577a9.png)



[error_log.txt](https://github.com/mevdschee/php-crud-api/files/727714/error_log.txt)

**Comment by mevdschee** [comment] 2017-01-24 19:38
Are you sure the file is uploaded properly? Can you use another method of putting the file on the server? It indeed still seems like the anonymous function is not properly interpreted as it still says:

    preg_replace_callback(): Requires argument 2, '', to be a valid callback

Note that the error log may contain sensitive information.

**Comment by rajurk2000** [comment] 2017-01-24 20:05
Refer below output.
Secondly, extracted API file from Zip file and copier on c:/ drive, and edited using note pad. and then uploaded. but same error msg. Not found (entity)

but when change format to JSON Getting error msg.  Unexpected 'N'

[24-Jan-2017 19:59:07 Etc/GMT] PHP Warning:  preg_replace_callback(): Requires argument 2, '', to be a valid callback in /home/uponcje1/public_html/crud/api.php on line 139


![image](https://cloud.githubusercontent.com/assets/7404630/22263838/d7bc1afe-e29b-11e6-8361-9fd45f10ee7c.png)


![image](https://cloud.githubusercontent.com/assets/7404630/22264579/7f17d2dc-e29e-11e6-9211-8bac49107363.png)


![image](https://cloud.githubusercontent.com/assets/7404630/22264530/4f9e0094-e29e-11e6-88da-09d4372587ff.png)

**Comment by mevdschee** [comment] 2017-01-24 20:15
Can you try the following code to see whether or not all anonymous functions are broken?

```
<?php
$string = "Some numbers: one: 1; two: 2; three: 3 end";
$ten = 10;
$newstring = preg_replace_callback(
    '/(\\d+)/',
    function($match) use ($ten) { return (($match[0] + $ten)); },
    $string
    );
echo $newstring;
#prints "Some numbers: one: 11; two: 12; three: 13 end"; 
```

This issue is getting weirder and weirder... a challenge ;-)

**Comment by rajurk2000** [comment] 2017-01-24 20:30
refer below out put, hope this is correct way to execute code.

![image](https://cloud.githubusercontent.com/assets/7404630/22265269/609eebe4-e2a1-11e6-840e-acba17e8d759.png)


![image](https://cloud.githubusercontent.com/assets/7404630/22265372/d64b33ac-e2a1-11e6-8cc5-a8ddb5361f62.png)


![image](https://cloud.githubusercontent.com/assets/7404630/22265425/fc884e1a-e2a1-11e6-9937-2757791dd593.png)

**Comment by mevdschee** [comment] 2017-01-24 20:31
okay.. anonymous functions are not working at all on your setup..

**Comment by rajurk2000** [comment] 2017-01-24 20:42
after replacing  '&$ten' with '$ten'  and refer output of error.log file

![image](https://cloud.githubusercontent.com/assets/7404630/22265713/41300912-e2a3-11e6-88e8-b321d37fe699.png)


output of send file test2.php

![image](https://cloud.githubusercontent.com/assets/7404630/22265744/62e0709c-e2a3-11e6-8c3c-acca31bfa1cf.png)



24-Jan-2017 20:26:04 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 534507081 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:26:15 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 534737593 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:26:43 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 534743889 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:27:27 Etc/GMT] PHP Parse error:  syntax error, unexpected '"Some numbers: one: 11; two: 1' (T_CONSTANT_ENCAPSED_STRING) in /home/uponcje1/public_html/crud/test.php on line 10
[24-Jan-2017 20:27:38 Etc/GMT] PHP Parse error:  syntax error, unexpected '"Some numbers: one: 11; two: 1' (T_CONSTANT_ENCAPSED_STRING) in /home/uponcje1/public_html/crud/test.php on line 10
[24-Jan-2017 20:28:04 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 534743889 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:28:44 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 534754969 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:29:33 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 534744385 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:29:49 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 534733081 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:38:04 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 515169865 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:41:02 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4199308489 bytes) in /home/uponcje1/public_html/crud/test2.php on line 7
[24-Jan-2017 20:41:07 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4199304705 bytes) in /home/uponcje1/public_html/crud/test.php on line 8
[24-Jan-2017 20:41:19 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4199301457 bytes) in /home/uponcje1/public_html/crud/test2.php on line 7
[24-Jan-2017 20:41:34 Etc/GMT] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4199541929 bytes) in /home/uponcje1/public_html/crud/test2.php on line 7

**Comment by mevdschee** [comment] 2017-01-24 20:49
wow.. and how about the following code?

    <?php
    echo "Hello world!";
    //prints "Hello world!";

Does that also not work? This seems to be more elemental than I thought..

**Comment by rajurk2000** [comment] 2017-01-24 20:56
it is working, refer below output.

i feel some issue with my environment. let me check and revert you.

once again millions of thanks for you support and dedication to work.

![image](https://cloud.githubusercontent.com/assets/7404630/22266297/8d80e028-e2a5-11e6-8c95-e4e65e94bb68.png)

**Comment by mevdschee** [comment] 2017-01-24 20:58
>i feel some issue with my environment. let me check and revert you.

Yes, most definitely.. that code was straight from the PHP manual.

**Comment by rajurk2000** [comment] 2017-01-24 22:30
Hi, Congratulation !!!,

Thanks, same code is working on some other environment

https://swaninfotech.com/crud/api.php/bookingsheet/1

can you advice me how to use post method POST JSON data to above create api. 

for example : 
http://swaninfotech.com/crud/api.php/bookingsheet/[{"CustomerName":"ABCL"},{"City":"Prarkview"},{"product":"Web development"}]

**Comment by rajurk2000** [comment] 2017-01-24 22:31
Secondly, how to use php-crud-ui

**Comment by mevdschee** [comment] 2017-01-24 22:45
>POST JSON data to above create api.

POST requests should be issued using postman. See: https://www.youtube.com/watch?v=jBjXVrS8nXs (2:30)

>how to use php-crud-ui

Please open an issue on that project for support with a specific question.

**Comment by mevdschee** [comment] 2017-01-24 22:48
Closing this issue. Please open a new issue when addressing a new topic.

**Closed** 2017-01-24 22:47 UTC
Labels: bug
