### ISSUE TITLE
Support for fields containing JSON objects

### ISSUE THREAD

**Issue by cooperdk** [mevdschee/php-crud-api#723] opened 2020-10-29 04:52 UTC
Hi,

I have in my table a field which consists of a JSON object (a list of objects). The db is created manually and the field is a text field.
The tags editor is made in PHPrunner which creates a list with objects of uploaded files, and in the db it looks like JSON. For example:

`[{"name":"photos\/0003-01.jpg","usrName":"0003-01.jpg","size":77809,"type":"image\/jpeg","thumbnail":"thumbs\/0003-01.jpg","thumbnail_type":"image\/jpeg","thumbnail_size":6653,!:sStrEnd"}]`

I have the need to make the API output this as part of the JSON, currently it looks like this (the interesting bit is the "image" value which should be unquoted and unescaped by the API, since it's already escaped where it has to be):

```
{
    "records": [
        {
            "id": 529,
            "tag": "some tag",
            "image": "[{\"name\":\"photos\\\/0529-01.jpg\",\"usrName\":\"0529-01.jpg\",\"size\":68756,\"type\":\"image\\\/jpeg\",\"thumbnail\":\"thumbs\\\/0529-01.jpg\",\"thumbnail_type\":\"image\\\/jpeg\",\"thumbnail_size\":6820,!:sStrEnd\"},{\"name\":\"photos\\\/0529-02.jpg\",\"usrName\":\"0529-02.jpg\",\"size\":80947,\"type\":\"image\\\/jpeg\",\"thumbnail\":\"thumbs\\\/0529-02.jpg\",\"thumbnail_type\":\"image\\\/jpeg\",\"thumbnail_size\":6539},{\"name\":\"photos\\\/0529-03.jpg\",\"usrName\":\"0529-03.jpg\",\"size\":195495,\"type\":\"image\\\/jpeg\",\"thumbnail\":\"thumbs\\\/0529-03.jpg\",\"thumbnail_type\":\"image\\\/jpeg\",\"thumbnail_size\":12492}]",
            "description": "Some description",
            "priority": null,
            "slug": null,
            "added": "2020-10-05 15:00:00",
            "last_updated": "2020-10-20 00:14:01",
            ...
```

Is there a possibility to exclude this field from string parsing?

Thanks a lot, by the way, your software is great.

**Comment by cooperdk** [comment] 2020-11-12 09:57
I just wanted to add that I just converted the field from a TEXT field to a JSON field. This made no difference, so the code isn't able to handle MySQL JSON fields properly.

**Comment by mevdschee** [comment] 2020-11-12 10:00
Thank you for creating this issue. It is a very valid request. It is in fact a duplicate of #667, so I'm closing it here. Let's continue the discussion on that issue.

**Closed by mevdschee** 2020-11-12 10:00 UTC
Labels: enhancement

**Comment by cooperdk** [comment] 2020-11-12 23:09
That is great, I just commented in #667.
